### ISSUE TITLE
Cannot bind parameter "Encoding" - Cannot be converted from "UTF8NoBOM" to type "Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding"

### ISSUE THREAD

**Issue by habakuk007** [ajoberstar/ArchitectureDecisionRecords#6]
Hello,

I tried to use it on Windows 10 with PowerShell 5.1 (the one that opens by default) I get the following error if I try to run `Initialize-Adr`:

    Get-Content : Der Parameter "Encoding" kann nicht gebunden werden. Der Wert "UTF8NoBOM" kann nicht in den Typ
    "Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding" konvertiert werden. Fehler: "Der Bezeichner
    "UTF8NoBOM" kann keinem gültigen Enumeratornamen zugeordnet werden. Geben Sie einen der folgenden
    Enumeratornamen an, und wiederholen Sie den Vorgang:
    Unknown, String, Unicode, Byte, BigEndianUnicode, UTF8, UTF7, UTF32, Ascii, Default, Oem, BigEndianUTF32"
    In C:\Program
    Files\WindowsPowerShell\Modules\ArchitectureDecisionRecords\0.2.0\ArchitectureDecisionRecords.psm1:69 Zeichen:45

    Set-Content : Der Parameter "Encoding" kann nicht gebunden werden. Der Wert "UTF8NoBOM" kann nicht in den Typ
    "Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding" konvertiert werden. Fehler: "Der Bezeichner
    "UTF8NoBOM" kann keinem gültigen Enumeratornamen zugeordnet werden. Geben Sie einen der folgenden
    Enumeratornamen an, und wiederholen Sie den Vorgang:
    Unknown, String, Unicode, Byte, BigEndianUnicode, UTF8, UTF7, UTF32, Ascii, Default, Oem, BigEndianUTF32"
    In C:\Program
    Files\WindowsPowerShell\Modules\ArchitectureDecisionRecords\0.2.0\ArchitectureDecisionRecords.psm1:408 Zeichen:56

Regards!
   Stefan

**Comment by ajoberstar** [comment]
Looks like a duplicate of #1
