### ISSUE TITLE
1.0.0 is not in the Powershell Gallery

### ISSUE THREAD

**Issue by bigolewannabe** [ajoberstar/ArchitectureDecisionRecords#7]
I see v 1.0 came out a while back but 0.2.1 is the current one listed on PowerShell Gallery

https://www.powershellgallery.com/packages/ArchitectureDecisionRecords

**Comment by ajoberstar** [comment]
Oh, maybe I forgot to run the release when I tagged v1. I'll put that on my list.

**Comment by ajoberstar** [comment]
Thought there aren't any functional changes from v0.2.1, so you aren't missing out on anything

**Comment by bigolewannabe** [comment]
I saw that. I'm doing some advocacy work on them and 0.2.1 vs 1.0.0 is just one less thing to deal with. 

Thanks for looking into it.

**Comment by ajoberstar** [comment]
Uploaded 1.0.0 to the gallery now.
